### ISSUE TITLE
Add Gitter

### ISSUE THREAD

**Issue by felixfbecker** [cmpaul/vscode-php-debug#3]
Hi, I would like to contribute since I'm interested in this. I'm not familiar though with the VS Code debug extension API. Maybe you can create a Gitter room for discussion? Btw, does this work already?

**Comment by cmpaul** [comment]
@felixfbecker Done! Sent you an invite and also added a Gitter badge to the readme.

This does NOT work yet. I'm picking at it a bit every weekend, but please feel free to contribute as you see fit. Thanks!
